language: python

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"

install:
  - pip install pip==18.1
  - python get-poetry.py --preview -y
  - source $HOME/.poetry/env
  - poetry install -v

script: pytest -q tests/

matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial
