language: python

os:
  - linux
  - osx

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"

install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry install

script: pytest -q tests/

matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial
